repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-toml
    -   id: check-added-large-files
    -   id: debug-statements
    -   id: detect-private-key
-   repo: https://github.com/pycqa/autoflake
    rev: v2.1.1
    hooks:
    -   id: autoflake
- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
  - id: isort
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/flake8
    rev: 5.0.0
    hooks:
    -   id: flake8
        additional_dependencies: [
            darglint==1.8.1,
            flake8-bandit==4.1.1,
            flake8-isort==6.0.0,
            flake8-black==0.3.6,
            flake8-pyproject==1.2.3,
        ]
        verbose: true
